### ISSUE TITLE
Factories turning into Plastic ones after loading of save game

### ISSUE THREAD

**Issue by NZ-Wanderer** [Dr-DaNk/STAMaterialFactories#1]
I had 4 factories, one of each type, however this morning when I loaded a save game, all of those factories had turned into plastic ones..
It wouldn't have been to bad, except for the fact then when I demolished them to rebuild them again all the corn used to build them originally was not recovered :(

**Comment by nikko-guy** [comment]
General consensus of this issue is that it is an issue with the game, not the mod. Sources described even buildings from other mods turning into the plastic factory.
